const cvt_115_exam2 = [
  "LV increased depth, 2D (clip)",
  "LV optimized sector depth, 2D (clip)",
  "LV optimized sector depth 2D + color MV/AOV (clip)",
  "Linear measurements: RVIDd, IVSd, LVEDd, LVPWd (still)",
  "Linear measurement LVIDs (still)",
  "M-mode AOV & LA (still)",
  "M-mode MV (still)",
  "M-mode LV (still)",
  "Zoomed MV, 2D (be sure to include LVOT as landmark) (clip)",
  "Zoomed MV, 2D + color (clip)",
  "Zoomed LVOT/AV, 2D (clip)",
  "Linear measurement zoomed LVOT & AOV Annulus diameter (mid-systole) (still)",
  "Zoomed LVOT/AV, 2D + color (clip)",
  "Zoomed SOV/STJ /AscAo, 2D (clip)",
  "Linear measurement SOV & STJ diameter (end-diastole) (still)",
  "Zoomed SOV/STJ /AscAo, 2D + color (clip)",
  "Focused or Zoom Asc Ao, 2D (clip)",
  "Linear measurement Asc Ao diameter (end-diastole) (still)",
  "RV inflow, 2D (show TV POSTERIOR leaflet) (clip)",
  "RV inflow, 2D + color (clip)",
  "RV inflow (if TR present, measure CW Doppler peak velocity) (still)",
  "RVOT/Sub Pulmonic, 2D (clip)",
  "RVOT/Sub Pulmonic, 2D + color (clip)",
  "PA CW Doppler (measure PR @ end-diastole if present) (still)",
  "PSAX at BASE: Large-sector view, 2D (clip)",
  "PSAX at BASE: Large-sector view, 2D + color (clip)",
  "RVOT, linear measurement proximal RVOT (end-diastole) (still)",
  "Narrow-sector or Zoom TV, right atrium, RV inflow, 2D (clip)",
  "Narrow-sector or Zoom right atrium, TV, RV inflow, 2D + color (clip)",
  "Narrow-sector or Zoom right atrium, TV, if TR present measure CW Doppler peak velocity (still)",
  "AoV zoomed view showing valve leaflets, 2D (clip)",
  "AoV zoomed view, 2D + color (clip)",
  "Great vessels (superior to AoV, focused on PV, PA, and branches), 2D (clip)",
  "Great Vessels, Narrow sector or Zoom RVOT, PV, PA, 2D (clip)",
  "Distal RVOT & Main PA, linear measurements (end-diastole) (still)",
  "Great Vessels, Narrow sector or Zoom RVOT, PV, PA, 2D + Color (clip)",
  "RVOT, PW Doppler measure VTI (still)",
  "PA CW Doppler measure VTI (measure PR @ end-diastole if present) (still)",
  "MV leaflet level, 2D (clip)",
  "MV leaflet level, 2D + color (clip)",
  "LV mid papillary muscle level, 2D (clip)",
  "LV mid papillary muscle level, 2D + color (clip)",
  "LV apex level, 2D (clip)",
  "LV apex level, 2D + color (clip)",
  "VSD sweep from base to LV apex, 2D + color (clip)",
];
export default cvt_115_exam2;
