const parast_apicals = 
[
    "LV increased depth, 2D (clip)",
    "LV optimized sector depth, 2D (clip)",
    "LV optimized sector depth 2D + color MV/AOV (clip)",
    "Linear measurements: RVIDd, IVSd, LVEDd, LVPWd (still)",
    "Linear measurement LVIDs (still)",
    "M-mode AOV & LA (still)",
    "M-mode MV (still)",
    "M-mode LV (still)",
    "Zoomed MV, 2D (be sure to include LVOT as landmark) (clip)",
    "Zoomed MV, 2D + color (clip)",
    "Zoomed LVOT/AV, 2D (clip)",
    "Linear measurement zoomed LVOT & AOV Annulus diameter (mid-systole) (still)",
    "Zoomed LVOT/AV, 2D + color (clip)",
    "Zoomed SOV/STJ /AscAo, 2D (clip)",
    "Linear measurement SOV & STJ diameter (end-diastole) (still)",
    "Zoomed SOV/STJ /AscAo, 2D + color (clip)",
    "Focused or Zoom Asc Ao, 2D (clip)",
    "Linear measurement Asc Ao diameter (end-diastole) (still)",
    "RV inflow, 2D (show TV POSTERIOR leaflet) (clip)",
    "RV inflow, 2D + color (clip)",
    "RV inflow (if TR present, measure CW Doppler peak velocity) (still)",
    "RVOT/Sub Pulmonic, 2D (clip)",
    "RVOT/Sub Pulmonic, 2D + color (clip)",
    "PA CW Doppler (measure PR @ end-diastole if present) (still)",
    "PSAX at BASE: Large-sector view, 2D (clip)",
    "PSAX at BASE: Large-sector view, 2D + color (clip)",
    "RVOT, linear measurement proximal RVOT (end-diastole) (still)",
    "Narrow-sector or Zoom TV, right atrium, RV inflow, 2D (clip)",
    "Narrow-sector or Zoom right atrium, TV, RV inflow, 2D + color (clip)",
    "Narrow-sector or Zoom right atrium, TV, if TR present measure CW Doppler peak velocity (still)",
    "AoV zoomed view showing valve leaflets, 2D (clip)",
    "AoV zoomed view, 2D + color (clip)",
    "Great vessels (superior to AoV, focused on PV, PA, and branches), 2D (clip)",
    "Great Vessels, Narrow sector or Zoom RVOT, PV, PA, 2D (clip)",
    "Distal RVOT & Main PA, linear measurements (end-diastole) (still)",
    "Great Vessels, Narrow sector or Zoom RVOT, PV, PA, 2D + Color (clip)",
    "RVOT, PW Doppler measure VTI (still)",
    "PA CW Doppler measure VTI (measure PR @ end-diastole if present) (still)",
    "MV leaflet level, 2D (clip)",
    "MV leaflet level, 2D + color (clip)",
    "LV mid papillary muscle level, 2D (clip)",
    "LV mid papillary muscle level, 2D + color (clip)",
    "LV apex level, 2D (clip)",
    "LV apex level, 2D + color (clip)",
    "VSD sweep from base to LV apex, 2D + color (clip)",
    "A4C, 2D (clip)",
    "A4C: CS, 2D (clip)",
    "A4C, 2D + long color box to cover PVeins, MV, LV (clip)",
    "Zoom LA, 2D include MV & Pulm Veins (clip)",
    "Zoom LA volume (trace left atrium at end-systole, measure long-axis length) (still)",
    "Zoom LA, 2D + color optimized for Pulm Veins (clip)",
    "Zoom LA: Pulm Vein PW Doppler (show S, D, and A velocity waveforms) (still)",
    "Zoom LA MV, 2D + color optimized for MV flow (clip)",
    "Zoom LA: MV inflow, PW Doppler @ leaflet tips (measure E, E decel time, A) (still)",
    "Zoom LA: MV inflow, CW Doppler (trace for VTI & mean gradient) (still)",
    "if MR present then CW Doppler through MV (measure peak velocity and VTI) (still)",
    "DTI, MV lateral annulus (measure e′, a′, s′) (still)",
    "DTI, MV medial annulus (measure e′, a′, s′) (still)",
    "A4C, ventricular focus (adjusted sector width, depth and focus), 2D (clip)",
    "A4C ventricular focus, biplane summation of disks measure LV volume at end-diastole (still)",
    "A4C ventricular focus, biplane summation of disks measure LV volume at end-systole (still)",
    "A4C, 2D ventricular focus (adjusted sector width, depth and focus), sweep for apical thrombus (clip)",
    "TV, 2D + color inflow (clip)",
    "TV inflow PW Doppler (measure E velocity, A velocity) (still)",
    "CW Doppler for TR (if present, measure peak velocity) (still)",
    "M-mode-TAPSE (still)",
    "DTI TV lateral annulus s′, e′, a′ (still)",
    "RV-focused, 2D (clip)",
    "RV-focused view measure length, maximum basal transverse diameter, midcavity diameter at end-diastole (still)",
    "5C, 2D (clip)",
    "5C AoV and LVOT, 2D + color (clip)",
    "5C PW Doppler LVOT (trace VTI) (still)",
    "5C CW Doppler AoV (trace VTI) (still)",
    "A2C, 2D (clip)",
    "A2C MV, 2D + color (clip)",
    "Zoom LA, 2D (clip)",
    "Zoom LA (trace LA Vol end-systole) (still)",
    "A2C ventricular focus (adjusted sector width, depth and focus), 2D (clip)",
    "A2C ventricular focus, biplane summation of disks measure LV volume at end-diastole (still)",
    "A2C ventricular focus, biplane summation of disks measure LV volume at end-systole (still)",
    "Apical long-axis, 2D (clip)",
    "Apical long-axis, 2D + color (cover both MV and LVOT/AoV) (clip)",
    "Apical long-axis ventricular focus (adjusted sector width and depth), 2D (clip)"
  ]

  export default parast_apicals